"""Core models returned by imquest."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(slots=True)
class PhotoResult:
    """Normalized image search result from any provider."""

    id: str
    provider: str
    url: str
    width: int | None = None
    height: int | None = None
    photographer: str | None = None
    thumbnail_url: str | None = None
    location: str | None = None


@dataclass(slots=True)
class GeneratedImage:
    """Represents an image generated by an AI provider."""

    provider: str
    prompt: str
    revised_prompt: str | None
    image_bytes: bytes
    mime_type: str = "image/png"
